[project]
name = "game_test"
version = "0.1.0"
description = "Flappy Bird game using Streamlit"
requires-python = ">=3.8"
dependencies = [
    "streamlit>=1.28.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"